#!/usr/bin/env node
// Emit lib/client.js — the lazy-CJS bundle DSH's client module system loads.
//
// Why a hand-rolled bundler instead of rollup/esbuild:
//   * The host serves a *built* client bundle, and it must be wrapped in the
//     exact `window.__ModuleLoader__.load({ id, factory })` envelope with every
//     module side effect inside the factory (verified against the shipped
//     bundles, e.g. `@deepseek-ai/dsh-client-ui-jobs/lib/client.js`).
//   * This plugin is a handful of small CommonJS modules. A local module table
//     plus a `require` that falls through to the platform table is the whole
//     job, and it keeps the package free of build dependencies.
//   * `@deepseek-ai/dsh-client-modules` resolves each dynamic bundle's externals
//     against the frozen PLATFORM_MODULES table, so `react` here is the same
//     React instance the shell already loaded.
//
// Every source below is authored as CommonJS precisely so this script never has
// to transform anything: it inlines text. The host-only modules (src/index.js,
// src/detect.js, src/store.js, src/install.js) are ESM and deliberately NOT
// bundled — the browser half is a pure renderer and shares no code with the host
// half.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const pkgRoot = join(here, '..')
const manifest = JSON.parse(readFileSync(join(pkgRoot, 'package.json'), 'utf8'))

/**
 * Internal module table, keyed by the exact specifier the sources use.
 *
 * Every `require('./x.js')` in the client sources must appear here with the same
 * string, or the factory falls through to the platform table and throws.
 */
const MODULES = [
  { id: './theme.js', file: 'src/client/theme.js' },
  { id: './polish.js', file: 'src/client/polish.js' },
  { id: './icons.js', file: 'src/client/icons.js' },
  { id: './source.js', file: 'src/client/source.js' },
  { id: './api.js', file: 'src/client/api.js' },
  { id: './install.js', file: 'src/client/install.js' },
  { id: './panel.js', file: 'src/client/panel.js' },
]

const ENTRY = { id: './index.js', file: 'src/client/index.js' }

const indent = (text, pad) =>
  text
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : pad + line))
    .join('\n')

/**
 * Escape every non-ASCII code point as `\uXXXX`.
 *
 * The bundle is delivered to the browser over HTTP, and a script's encoding is
 * inferred from context. Emitting pure ASCII makes the artifact immune to any
 * charset mismatch — important because this plugin's UI strings are Chinese.
 * The sources only ever contain non-ASCII inside comments and string literals,
 * where a `\u` escape is exactly equivalent.
 */
function toAsciiSafe(text) {
  let out = ''
  for (const char of text) {
    const code = char.codePointAt(0)
    if (code <= 0x7e) {
      out += char
    } else if (code <= 0xffff) {
      out += `\\u${code.toString(16).padStart(4, '0')}`
    } else {
      const offset = code - 0x10000
      out += `\\u${(0xd800 + (offset >> 10)).toString(16)}\\u${(0xdc00 + (offset & 0x3ff)).toString(16)}`
    }
  }
  return out
}

const read = (rel) => {
  const abs = join(pkgRoot, rel)
  if (!existsSync(abs)) throw new Error(`missing source file: ${rel}`)
  return readFileSync(abs, 'utf8')
}

const table = []
for (const mod of [...MODULES, ENTRY]) {
  const source = read(mod.file)
  if (/^\s*(?:import|export)\s/m.test(source)) {
    throw new Error(`${mod.file}: client sources must be CommonJS (no import/export) — the bundler only inlines text`)
  }
  if (!/module\.exports\s*=/.test(source)) {
    throw new Error(`${mod.file}: client source never assigns module.exports`)
  }
  table.push(
    `\t\t\t${JSON.stringify(mod.id)}: function (module, exports, require) {\n` +
      `\t\t\t\t// ${mod.file}\n` +
      `${indent(source.trimEnd(), '\t\t\t\t')}\n` +
      `\t\t\t},`,
  )
}

const bundle = `// ${manifest.name}@${manifest.version} — generated by tools/build-client.mjs. Do not edit.
//
// Lazy CommonJS bundle for the DSH client module system: loading this file only
// registers the factory; the module bodies run when the factory is materialized.
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(manifest.name)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
\t\t// Internal modules, keyed by the specifier the sources use.
\t\tvar __modules = {
${table.join('\n')}
\t\t};
\t\tvar __cache = {};
\t\t/**
\t\t * Resolve an internal specifier from the table, otherwise delegate to the
\t\t * platform module table the shell handed us (react, react/jsx-runtime, ...).
\t\t */
\t\tfunction __require(id) {
\t\t\tif (Object.prototype.hasOwnProperty.call(__modules, id)) {
\t\t\t\tif (__cache[id] !== void 0) return __cache[id].exports;
\t\t\t\tvar record = { exports: {} };
\t\t\t\t__cache[id] = record;
\t\t\t\t__modules[id](record, record.exports, __require);
\t\t\t\treturn record.exports;
\t\t\t}
\t\t\treturn require(id);
\t\t}
\t\tmodule.exports = __require(${JSON.stringify(ENTRY.id)});
\t\treturn module.exports;
\t}
});
`

const dist = join(pkgRoot, 'lib')
mkdirSync(dist, { recursive: true })
const target = join(dist, 'client.js')
writeFileSync(target, toAsciiSafe(bundle), 'utf8')

const written = readFileSync(target, 'utf8')
const nonAscii = [...written].filter((c) => c.codePointAt(0) > 0x7e).length
if (nonAscii > 0) throw new Error(`lib/client.js still contains ${nonAscii} non-ASCII code points`)

// Parse the artifact before declaring success.
//
// Nothing in this build transforms anything — the sources are inlined as text — so
// a stray backtick inside a template literal (an easy accident in a CSS comment)
// closes that literal early and yields a file this script would otherwise write
// happily. The browser then throws SyntaxError at load time, which surfaces as a
// silently broken plugin. `new Function` parses without running the body, so the
// `window.__ModuleLoader__` call inside is never evaluated.
try {
  // eslint-disable-next-line no-new-func
  new Function(written)
} catch (error) {
  throw new Error(
    `lib/client.js does not parse — it would throw at load time: ${error.message}\n` +
      '  Usual cause: a stray backtick inside a template literal (a CSS comment is the easy place to do it).',
  )
}

console.log(`${manifest.name}@${manifest.version}: wrote lib/client.js`)
console.log(`  ${MODULES.length + 1} internal modules, ${written.length} bytes, pure ASCII`)
for (const mod of [...MODULES, ENTRY]) console.log(`    ${mod.id.padEnd(14)} <- ${mod.file}`)
